# build docker image for arm32
# this script is WIP.
sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- apt install qemu-user-static binfmt-support
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t jlapp:rpi3 ./rpi3/jl_official
