version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - setup_remote_docker:
          # we can see available docker version
          # https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 18.06.0-ce
          docker_layer_caching: true
      - checkout
      - run:
          name: login docker
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: build julia
          command: |
            docker build -t ${DOCKER_USER}/jlapp:rpi3 ./rpi3
      - run:
          name: push to dockerhub
          command: |
            docker push ${DOCKER_USER}/jlapp:rpi3
