version: 2
jobs:
  build:
    # set machine
    machine: true
    steps:
      - checkout
      - run:
          name: Enable qemu
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: login docker
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: build julia cross
          command: |
            docker build -t ${DOCKER_USER}/jlapp:rpi3-jl-xc ./rpi3/jl_cross
      - run:
          name: build julia official
          command: |
            docker build -t ${DOCKER_USER}/jlapp:rpi3-jl-official ./rpi3/jl_official
      - run:
          name: push to dockerhub
          command: |
            docker push ${DOCKER_USER}/jlapp:rpi3
